version: "3.5"

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "6222:6222"
      - "4222:4222"
    command: "-js --server_name nats -m 8222"

  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"
  
  service.datastore:
    build: ./
    command: start datastore --auto-migrate
    depends_on:
      - nats
      - scylla
    environment:
      - ACKSTREAM_ENV=dev
      - ACKSTREAM_STREAM_URI=nats://nats
      - ACKSTREAM_STORAGE_HOSTS=scylla
      - ACKSTREAM_STREAM_QUEUE=docker-compose
